# Generated by Django 4.0.3 on 2023-03-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_sale_automobile_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rest.salespersons'),
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
    ]
