# Generated by Django 4.0.3 on 2023-03-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_salespersons_alter_sale_sales_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rest.automobilevo'),
        ),
        migrations.DeleteModel(
            name='Automobile',
        ),
    ]
