# Generated by Django 4.0.3 on 2023-03-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_automobile_alter_sale_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rest.automobilevo'),
        ),
        migrations.DeleteModel(
            name='Automobile',
        ),
    ]
