# Generated by Django 4.0.3 on 2023-03-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vin',
            field=models.CharField(default=0, max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
