# Generated by Django 4.0.3 on 2023-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_service_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='appointment_time',
            field=models.DateTimeField(null=True),
        ),
    ]
