# Generated by Django 4.0.3 on 2023-03-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_tech_service_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
